name: transaction_app_flutter
description: A Flutter port of the transaction tracker app.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  intl: ^0.18.0
  shared_preferences: ^2.0.19
  flutter_local_notifications: ^17.2.1
  google_generative_ai: ^0.4.0
  local_auth: ^2.2.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/splash-icon.png
